baseURL = "https://fahrizblog.netlify.com/"
languageCode = "en-us"
title = "Fahriz Coding"
theme = "kross-hugo-portfolio-template"
summaryLength = "10"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"


# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 3
  
  [[menu.main]]
  name = "Java"
  URL = "java"
  weight = 4
  
  [[menu.main]]
  name = "Web Developer"
  URL = "webdev"
  weight = 5


[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  [params.contact]
  enable = true
  formAction = "#" #contact form works with formspree.io

  [params.footer]
  email = "dimasqy.fahriz@gmail.com"
  phone = "085312858608"
  address = "Bandung"
